version: '3.8'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: ["./docker/wait-for-db.sh", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/demo
      EMBEDDING_PROVIDER: LOCAL
      LLM_PROVIDER: LOCAL
      OPENAI_CHAT_MODEL: ${OPENAI_CHAT_MODEL:-gpt-4o}
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./db:/app/db
      - ./models:/models

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://api:8000
    depends_on:
      - api
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host

volumes:
  pgdata:
    driver: local

